workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - david reference name
      groups:
        - keystore_credentials
      vars:
        KEYSTORE_PATH: /tmp/keystore.keystore
    scripts:
      - name: Prepare code signing
        script: echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release
      - name: Build universal apk
        script: |
          android-app-bundle build-universal-apk \
            --bundle 'build/app/outputs/bundle/release/app-release.aab' \
            --ks $CM_KEYSTORE_PATH \
            --ks-pass $CM_KEYSTORE_PASSWORD \
            --ks-key-alias $CM_KEY_ALIAS \
            --key-pass $CM_KEY_PASSWORD
      - name: Build Android release
        script: |
          flutter build appbundle --release \
            --build-name=1.0.5 \
            --build-number=5
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dtrdic2@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_token: MS8vMDl0T3phMTBEN25FOENnWUlBUkFBR0FrU053Ri1MOUlybUdoOTV4SWJ6bUdJVWlQdWtJdHNNWjN3QTJ0T0VMT2s4bUsyNV9EY09pSnBnd3N1aWdyNE0xRng0VWNQclJlc1hnMA==
        android:
          app_id: 1:415099635189:android:ad5cbf6a24328db3b60cbc
