workflows:
  build-and-test:
    name: Build and Test
scripts:
  - echo "single line script"
  - name: Flutter test
    script: flutter test
    ignore_failure: true
  - |
    #!/usr/bin/env python3

    print('Multiline Python script')
  - name: Build for iOS
    script: flutter build ios
